server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#路由网关配置
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2   #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**    #断言，路径相匹配的进行路由

        # 通过9527网关跳转访问百度新闻
        - id: payment_routh3   #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://news.baidu.com    #匹配后提供服务的路由地址
          predicates:
            - Path=/**    #断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/

