server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #路由网关配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务明进行动态路由
      routes:
        - id: payment_routh #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
            - After=2021-11-05T09:35:54.329+08:00[Asia/Shanghai]  #在某个时刻之后的请求才生效，时间串的获得见test文件夹
            #- Before=2021-11-06T09:35:54.329+08:00[Asia/Shanghai]  #在某个时刻之前的请求才生效，时间串的获得见test文件夹
            #- Between=2021-11-06T09:35:54.329+08:00[Asia/Shanghai],2021-11-07T09:35:54.329+08:00[Asia/Shanghai] #在这两个时间之间的请求才生效
            #- Cookie=username,lbt  #在请求的时候必须带上这个k-v键值对才能请求成功
            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性，并且值为整数的正则表达式

        - id: payment_routh2   #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**    #断言，路径相匹配的进行路由

        # 通过9527网关跳转访问百度新闻
        - id: payment_routh3   #payment_route  #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://news.baidu.com    #匹配后提供服务的路由地址
          predicates:
            - Path=/**    #断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/

