server:
  port: 80

#服务名称----注册到zookeeper注册中心的名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 180.76.250.113:2181   #linux服务器上部署了zookeeper并启动，180.76.250.113是服务器的地址，2181是zookee